### ISSUE TITLE
version incompatibility

### ISSUE THREAD

**Issue by Robert-Muil** [quantumblacklabs/kedro-examples#7]
## Description
`ERROR: botocore 1.13.17 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7", but you'll have python-dateutil 2.8.1 which is incompatible.`

## Context
Attempting to do `pip install -r kedro_tutorial/src/requirements` in a fresh virtual env.

## Steps to Reproduce

1. conda create ...
2. pip install -r ...

## Expected Result
Full install of all requirements with no errors.

## Actual Result
Error.

```
ERROR: botocore 1.13.17 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7", but you'll have python-dateutil 2.8.1 which is incompatible.
```

## Your Environment
Include as many relevant details about the environment you experienced the bug in:

* Kedro-Example:
cloned on 2019-11-14 
* Kedro version used (`pip show kedro` or `kedro -V`):
na
* Python version used (`python -V`):
`Python 3.7.0`
* Operating system and version:
`Darwin LON-146770-C02YK107JGH8 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64`

**Comment by DmitriiDeriabinQB** [comment]
@Robert-Muil thank you for reporting this. `pip` throws this error, but in fact all the packages are installed despite the version incompatibility, so you should be able to `cd kedro-tutorial && kedro run`

To mitigate the error, we would recommend the following:
1. clone the repo
2. create and activate conda environment
3. `pip install kedro && cd kedro-tutorial`  - `pip` throws that version error, but continues the installations
4. `kedro build-reqs` - will freeze your requirements' versions
5. `kedro install` - install frozen deps
6. `kedro run`

**Comment by tolomea** [comment]
The key point to what @DmitriiDeriabinQB is suggesting is that the tool that freeze's the requirements does a much better job of resolving differing versions than pip does.

**Comment by Robert-Muil** [comment]
Thank you both for response. I don't quite understand the logic of this though: if the pip install works (and indeed is required for the `build-reqs` then what is the point of freezing and installing frozen deps? We will have to ignore the version error either way, right?

Also, I'm always a bit wary about freezing all requirements, including low-level libraries, as it's bad for security: we'd no longer get any updates at all, right?

**Comment by tolomea** [comment]
Pip does not do version resolution of the packages, it just installs things as it finds them. So if it finds a requirement for wobulator<=15.0 it will install wobulator 15.0, then if later it finds a requirement for wobulator <= 14.0 it will just shrug because it already has wobulator. This leaves your environment in a state where it might run but is technically in violation of some of the version requirements. And it produces errors and warnings.

There is another tool called pip-compile (part of the pip-tools pacakge) that does do version resolution. Pip-compile will find the two requirements and realize that 14.0 is the latest version that is compatible with both requirements.
Interface wise what pip-compile does is it takes the requirements file, resolves all the dependencies and writes out a new file with all the dependencies resolved.
Generally you use it with two requirements files so:
"requirements.in" -> pip-compile -> "requirements.txt" -> pip

Kedro build-reqs is short for this flow, the first time you run it it will copy your requirements.txt to requirements.in, from then on it will rebuild requirements.txt from requirements.in with the dependency versions correctly resolved.

In terms of updates everytime you run kedro build-reqs it will rebuild your requirements.txt with the latest versions. So you get the security updates when you want them. Rather than them just happening.
